kind = "DojoContract"
class_hash = "0x6bb808ee2d5cb80847ab75c5cc5036da67f59110f6ea6e05e4464e362de5f43"
original_class_hash = "0x6bb808ee2d5cb80847ab75c5cc5036da67f59110f6ea6e05e4464e362de5f43"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_contracts_item_item_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::contracts::item::item_actions"
