kind = "DojoContract"
class_hash = "0x4bac30ec5627544197bb305fd555fdab33bfbb63f5815fd44786d2930af5312"
original_class_hash = "0x4bac30ec5627544197bb305fd555fdab33bfbb63f5815fd44786d2930af5312"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_collections_blobert_blobert_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::collections::blobert::blobert_actions"
