kind = "DojoContract"
class_hash = "0x666b7f74eed2fda627b8b1c17b0ee39780cd99a29a1adb238bae33e3a6696dd"
original_class_hash = "0x666b7f74eed2fda627b8b1c17b0ee39780cd99a29a1adb238bae33e3a6696dd"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_contracts_attack_attack_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::contracts::attack::attack_actions"
