kind = "DojoContract"
class_hash = "0x7524d17d0fb2c50bec6d265385acb2a8b0cf685950190210a2e39f439ccae40"
original_class_hash = "0x7524d17d0fb2c50bec6d265385acb2a8b0cf685950190210a2e39f439ccae40"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_collections_blobert_blobert_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::collections::blobert::blobert_actions"
