kind = "DojoContract"
class_hash = "0x2cac7119d4bcca93477e331d972cfc019a95bd684198047a74ecf9f2b0ccd35"
original_class_hash = "0x2cac7119d4bcca93477e331d972cfc019a95bd684198047a74ecf9f2b0ccd35"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_contracts_pvp_pvp_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::contracts::pvp::pvp_actions"
