kind = "DojoContract"
class_hash = "0x44d77844cd2f5f88c49eba7bb0c356cab38a9331e9ba4ded0307d6ec3bf3796"
original_class_hash = "0x44d77844cd2f5f88c49eba7bb0c356cab38a9331e9ba4ded0307d6ec3bf3796"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_contracts_item_item_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::contracts::item::item_actions"
