kind = "DojoContract"
class_hash = "0x619f43d38e675ab7c216d2269612ac88c2e7323df0e15d474c48925ff80159f"
original_class_hash = "0x619f43d38e675ab7c216d2269612ac88c2e7323df0e15d474c48925ff80159f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/blob_arena_contracts_pvp_admin_pvp_admin_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "blob_arena::contracts::pvp_admin::pvp_admin_actions"
