[world]
name = "blob_arena"
seed = "blob-arena-0.13"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
keystore_path = "/home/ben/sn-accounts/0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec-keystore.json"


[init_call_args]
"blob_arena-game_admin" = []
"blobert-blobert_actions" = [
    "0x032cb9f30629268612ffb6060e40dfc669849c7d72539dd23c80fe6578d0549d",
]

[namespace]
default = "blob_arena"
mappings = { blob_arena = [
    "CombatantToken",
    "Tag",
], blobert = [
    "blobert_actions",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], free_blobert = [
    "free_blobert_actions",
    "LastMint",
    "BlobertToken",
], amma_blobert = [
    "amma_blobert_actions",
    "BlobertToken",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], arcade = [
    "arcade_actions",
    "arcade_admin_actions",
    "Tag",
    "CombatantToken",
    "ArcadeOpponent",
    "ArcadeCollectionAllowed",
    "ArcadeBlobertInfo",
    "ArcadeChallenge",
    "ArcadeChallengeName",
    "ArcadeStageOpponent",
    "ArcadeGame",
    "ArcadeFreeGames",
    "ArcadePaidGames",
    "ArcadeChallengeAttempt",
    "ArcadeStageGame",
    "ArcadeChallengeRespawn",
    "ArcadeCurrentChallengeAttempt",
], ba_permissions = [
    "Permission",
] }

[writers]
"blob_arena-Lobby" = ["blob_arena-lobby_actions"]
"blob_arena-LobbyCreated" = ["blob_arena-lobby_actions"]

"blob_arena-GameInfo" = ["blob_arena-lobby_actions", "blob_arena-game_admin"]
"blob_arena-Initiator" = ["blob_arena-lobby_actions", "blob_arena-game_admin"]

"blob_arena-CombatantToken" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]
"blob_arena-CombatantInfo" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]

"blob_arena-CombatantState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
    "arcade-arcade_actions",
]

"blob_arena-AttackAvailable" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
    "arcade-arcade_actions",
]

"blob_arena-AttackLastUsed" = [
    "blob_arena-game_actions",
    "arcade-arcade_actions",
]

"blob_arena-CombatState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
    "arcade-arcade_actions",
]

"blob_arena-Commitment" = ["blob_arena-game_actions"]
"blob_arena-LastTimestamp" = ["blob_arena-game_actions"]
"blob_arena-PlannedAttack" = ["blob_arena-game_actions"]
"blob_arena-CombatEnd" = ["blob_arena-game_actions"]
"ba_permissions-Permission" = ["blob_arena-game_admin"]

"blob_arena-RoundResult" = ["blob_arena-game_actions", "arcade-arcade_actions"]

"blob_arena-Attack" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]
"blob_arena-AttackName" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]

"blob_arena-Tag" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "arcade-arcade_admin_actions",
]

"arcade-ArcadeChallengeAttempt" = ["arcade-arcade_actions"]
"arcade-ArcadeStageGame" = ["arcade-arcade_actions"]
"arcade-ArcadeGame" = ["arcade-arcade_actions"]
"arcade-ArcadeFreeGames" = ["arcade-arcade_actions"]
"arcade-ArcadePaidGames" = ["arcade-arcade_actions"]
"arcade-ArcadeChallengeRespawn" = ["arcade-arcade_actions"]
"arcade-CombatantToken" = ["arcade-arcade_actions"]
"arcade-ArcadeCurrentChallengeAttempt" = ["arcade-arcade_actions"]

"blobert" = ["blobert-blobert_actions"]
"free_blobert" = ["free_blobert-free_blobert_actions"]
"amma_blobert" = ["amma_blobert-amma_blobert_actions"]
"arcade" = ["arcade-arcade_admin_actions"]
