[world]
name = "blob_arena"
seed = "dev"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[init_call_args]
"blobert-blobert_actions" = [
    "0x032cb9f30629268612ffb6060e40dfc669849c7d72539dd23c80fe6578d0549d",
]

[namespace]
default = "blob_arena"
mappings = { blob_arena = [
    "CombatantToken",
    "Tag",
    "AttackUses",
    "GamesCompleted",
], blobert = [
    "blobert_actions",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], free_blobert = [
    "free_blobert_actions",
    "LastMint",
    "BlobertToken",
    "AmountTokensOwned",
], amma_blobert = [
    "amma_blobert_actions",
    "BlobertToken",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], arcade = [
    "arcade_actions",
    "Tag",
    "CombatantToken",
    "ArcadeOpponent",
    "ArcadeCollectionAllowed",
    "ArcadeBlobertInfo",
    "ArcadeChallenge",
    "ArcadeChallengeName",
    "ArcadeStageOpponent",
    "ArcadeGame",
    "ArcadeFreeGames",
    "ArcadePaidGames",
    "ArcadeChallengeAttempt",
    "ArcadeStageGame",
    "ArcadeChallengeRespawn",
    "ArcadeCurrentChallengeAttempt",
    "AttackUses",
], ba_permissions = [
    "Permission",
], achievements = [
    "TrophyCreation",
    "TrophyProgression",
], testing = [
    "test_blobert_actions",
    "BlobertToken",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
] }

[writers]
"blob_arena-Lobby" = ["blob_arena-lobby_actions"]
"blob_arena-LobbyCreated" = ["blob_arena-lobby_actions"]

"blob_arena-GameInfo" = ["blob_arena-lobby_actions", "blob_arena-game_actions"]
"blob_arena-Initiator" = ["blob_arena-lobby_actions", "blob_arena-game_actions"]
"blob_arena-CombatantToken" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_actions",
]
"blob_arena-CombatantInfo" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_actions",
]

"blob_arena-AttackUses" = ["blob_arena-game_actions"]
"blob_arena-GamesCompleted" = ["blob_arena-game_actions"]

"blob_arena-CombatantState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "arcade-arcade_actions",
]

"blob_arena-AttackAvailable" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_actions",
    "arcade-arcade_actions",
]

"blob_arena-CombatState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "arcade-arcade_actions",
]

"blob_arena-AttackLastUsed" = [
    "blob_arena-game_actions",
    "arcade-arcade_actions",
]
"blob_arena-RoundResult" = ["blob_arena-game_actions", "arcade-arcade_actions"]

"blob_arena-Commitment" = ["blob_arena-game_actions"]
"blob_arena-LastTimestamp" = ["blob_arena-game_actions"]
"blob_arena-PlannedAttack" = ["blob_arena-game_actions"]
"blob_arena-CombatEnd" = ["blob_arena-game_actions"]

"blob_arena-Attack" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "testing-test_blobert_actions",
]
"blob_arena-AttackName" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "testing-test_blobert_actions",
]

"blob_arena-Tag" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "arcade-arcade_actions",
    "testing-test_blobert_actions",
]

"blob_arena-CollectionGroup" = [
    "blobert-blobert_actions",
    "free_blobert-free_blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "testing-test_blobert_actions",
]

"ba_permissions-Permission" = ["blob_arena-admin_actions"]

"achievements-TrophyCreation" = ["blob_arena-admin_actions"]
"achievements-TrophyProgression" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_actions",
    "arcade-arcade_actions",
]

"blobert" = ["blobert-blobert_actions"]
"free_blobert" = ["free_blobert-free_blobert_actions"]
"amma_blobert" = ["amma_blobert-amma_blobert_actions"]
"testing" = ["testing-test_blobert_actions"]

"arcade" = ["arcade-arcade_actions"]
