[world]
name = "blob_arena-0.8.8"
seed = "blob-arena-0.8.8"


[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
account_address = "0x049848982e9b089A1F4eb5e1cd12aB58bE55Feb6937bc9CfcAD34c2Dfd0a6df8"

[namespace]
default = "blob_arena"
mappings = { "blobert" = [
    "blobert_actions",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], "arcade_blobert" = [
    "arcade_blobert_actions",
    "LastMint",
    "BlobertToken",
], "amma_blobert" = [
    "amma_blobert_actions",
    "BlobertToken",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
] }

[writers]
"blob_arena-Lobby" = ["blob_arena-lobby_actions"]
"blob_arena-LobbyCreated" = ["blob_arena-lobby_actions"]

"blob_arena-GameInfo" = ["blob_arena-lobby_actions", "blob_arena-game_admin"]
"blob_arena-Initiator" = ["blob_arena-lobby_actions", "blob_arena-game_admin"]

"blob_arena-CombatantToken" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]
"blob_arena-CombatantInfo" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]

"blob_arena-CombatantState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]

"blob_arena-AttackAvailable" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]

"blob_arena-AttackLastUsed" = ["blob_arena-game_actions"]

"blob_arena-CombatState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "blob_arena-game_admin",
]

"blob_arena-Commitment" = ["blob_arena-game_actions"]
"blob_arena-LastTimestamp" = ["blob_arena-game_actions"]
"blob_arena-Salts" = ["blob_arena-game_actions"]
"blob_arena-PlannedAttack" = ["blob_arena-game_actions"]
"blob_arena-CombatEnd" = ["blob_arena-game_actions"]

"blob_arena-RoundResult" = ["blob_arena-game_actions"]

"blob_arena-Attack" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]
"blob_arena-AttackName" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]

"blobert" = ["blobert-blobert_actions"]
"arcade_blobert" = ["arcade_blobert-arcade_blobert_actions"]
"amma_blobert" = ["amma_blobert-amma_blobert_actions"]
