[world]
name = "blob_arena-0.12"
seed = "blob-arena-0.12.beef"


[env]
rpc_url = "https://api.cartridge.gg/rpc/starknet-sepolia"
account_address = "0x058e3B49d870f08C96a02f794C82b5f6C868c074DeaDD6bA04E8d2194723B5bd"
keystore_path = "/home/ben/sn-accounts/0x058e3b49d870f08c96a02f794c82b5f6c868c074deadd6ba04e8d2194723b5bd-keystore.json"

[init_call_args]
"blob_arena-game_admin_actions" = []
"blobert-blobert_actions" = [
    "0x032cb9f30629268612ffb6060e40dfc669849c7d72539dd23c80fe6578d0549d",
]

[namespace]
default = "blob_arena"
mappings = { blob_arena = [
    "CombatantToken",
    "Tag",
], blobert = [
    "blobert_actions",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], free_blobert = [
    "free_blobert_actions",
    "LastMint",
    "BlobertToken",
], amma_blobert = [
    "amma_blobert_actions",
    "BlobertToken",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], arcade = [
    "arcade_actions",
    "arcade_admin_actions",
    "Tag",
    "CombatantToken",
    "ArcadeOpponent",
    "ArcadeCollectionAllowed",
    "ArcadeBlobertInfo",
    "ArcadeChallenge",
    "ArcadeChallengeName",
    "ArcadeStageOpponent",
    "ArcadeGame",
    "ArcadeFreeGames",
    "ArcadePaidGames",
    "ArcadeChallengeAttempt",
    "ArcadeStageGame",
    "ArcadeChallengeRespawn",
    "ArcadeCurrentChallengeAttempt",
], ba_permissions = [
    "Permission",
] }

[writers]
"blob_arena-Lobby" = ["blob_arena-lobby_actions"]
"blob_arena-LobbyCreated" = ["blob_arena-lobby_actions"]

"blob_arena-GameInfo" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
]
"blob_arena-Initiator" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
]

"blob_arena-CombatantToken" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
]
"blob_arena-CombatantInfo" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
]

"blob_arena-CombatantState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
    "arcade-arcade_actions",
]

"blob_arena-AttackAvailable" = [
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
    "arcade-arcade_actions",
]

"blob_arena-AttackLastUsed" = [
    "blob_arena-game_actions",
    "arcade-arcade_actions",
]

"blob_arena-CombatState" = [
    "blob_arena-game_actions",
    "blob_arena-lobby_actions",
    "blob_arena-game_admin_actions",
    "arcade-arcade_actions",
]

"blob_arena-Commitment" = ["blob_arena-game_actions"]
"blob_arena-LastTimestamp" = ["blob_arena-game_actions"]
"blob_arena-PlannedAttack" = ["blob_arena-game_actions"]
"blob_arena-CombatEnd" = ["blob_arena-game_actions"]
"ba_permissions-Permission" = ["blob_arena-game_admin_actions"]

"blob_arena-RoundResult" = ["blob_arena-game_actions", "arcade-arcade_actions"]

"blob_arena-Attack" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]
"blob_arena-AttackName" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]

"blob_arena-Tag" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "arcade-arcade_admin_actions",
]

"arcade-ArcadeChallengeAttempt" = ["arcade-arcade_actions"]
"arcade-ArcadeStageGame" = ["arcade-arcade_actions"]
"arcade-ArcadeGame" = ["arcade-arcade_actions"]
"arcade-ArcadeFreeGames" = ["arcade-arcade_actions"]
"arcade-ArcadePaidGames" = ["arcade-arcade_actions"]
"arcade-ArcadeChallengeRespawn" = ["arcade-arcade_actions"]
"arcade-CombatantToken" = ["arcade-arcade_actions"]
"arcade-ArcadeCurrentChallengeAttempt" = ["arcade-arcade_actions"]

"blobert" = ["blobert-blobert_actions"]
"free_blobert" = ["free_blobert-free_blobert_actions"]
"amma_blobert" = ["amma_blobert-amma_blobert_actions"]
"arcade" = ["arcade-arcade_admin_actions"]
