[world]
name = "blob_arena"
seed = "dev"

[env]
rpc_url = "https://dev.grugslair.com/ba/katana"
account_address = "0x11655d28eb745d996ebfc2d0c0cab651c73c75fcf1a408b52d35de724306361"
keystore_path = "/home/ben/.starknet_accounts/0x11655d28eb745d996ebfc2d0c0cab651c73c75fcf1a408b52d35de724306361-keystore.json"

[init_call_args]
"blobert-blobert_actions" = [
    "0x032cb9f30629268612ffb6060e40dfc669849c7d72539dd23c80fe6578d0549d",
]

[namespace]
mappings = { blob_arena = [
    "CombatantToken",
    "Tag",
    "AttackUses",
    "PvpsCompleted",
], blobert = [
    "blobert_actions",
    "BlobertItem",
    "AttackSlot",
    "BlobertItemName",
], free_blobert = [
    "free_blobert_actions",
    "LastMint",
    "BlobertToken",
    "AmountTokensOwned",
], amma_blobert = [
    "amma_blobert_actions",
    "BlobertToken",
    "AttackSlot",
    "FirstTokenMinted",
    "ArcadeAttemptMinted",
    "AmmaFighter",
    "AmmaFighterName",
], arcade = [
    "arcade_actions",
    "Tag",
    "CombatantToken",
    "ArcadeOpponent",
    "ArcadeCollectionAllowed",
    "ArcadeBlobertInfo",
    "ArcadeChallenge",
    "ArcadeChallengeName",
    "ArcadeStageOpponent",
    "ArcadeGame",
    "ArcadeFreeGames",
    "ArcadePaidGames",
    "ArcadeChallengeAttempt",
    "ArcadeStageGame",
    "ArcadeChallengeRespawn",
    "ArcadeCurrentChallengeAttempt",
    "AttackUses",
], arcade_amma = [
    "arcade_amma_actions",
    "AmmaArcadeStageOpponent",
    "AmmaArcadeChallengeAttempt",
    "CombatantToken",
    "ArcadeGame",
    "ArcadeStageGame",
    "ArcadeChallengeRespawn",
    "AttackUses",
], ba_permissions = [
    "Permission",
], achievements = [
    "TrophyCreation",
    "TrophyProgression",
] }

default = "blob_arena"
[writers]
"blob_arena-Lobby" = ["blob_arena-lobby_actions"]
"blob_arena-LobbyCreated" = ["blob_arena-lobby_actions"]

"blob_arena-PvpInfo" = ["blob_arena-lobby_actions", "blob_arena-pvp_actions"]
"blob_arena-Initiator" = ["blob_arena-lobby_actions", "blob_arena-pvp_actions"]
"blob_arena-CombatantToken" = [
    "blob_arena-lobby_actions",
    "blob_arena-pvp_actions",
]
"blob_arena-CombatantInfo" = [
    "blob_arena-lobby_actions",
    "blob_arena-pvp_actions",
]

"blob_arena-AttackUses" = ["blob_arena-pvp_actions"]
"blob_arena-PvpsCompleted" = ["blob_arena-pvp_actions"]

"blob_arena-CombatantState" = [
    "blob_arena-pvp_actions",
    "blob_arena-lobby_actions",
    "arcade-arcade_actions",
    "arcade_amma-arcade_amma_actions",
]

"blob_arena-AttackAvailable" = [
    "blob_arena-lobby_actions",
    "blob_arena-pvp_actions",
    "arcade-arcade_actions",
    "arcade_amma-arcade_amma_actions",
]

"blob_arena-CombatState" = [
    "blob_arena-pvp_actions",
    "blob_arena-lobby_actions",
    "arcade-arcade_actions",
    "arcade_amma-arcade_amma_actions",
]

"blob_arena-AttackLastUsed" = [
    "blob_arena-pvp_actions",
    "arcade-arcade_actions",
    "arcade_amma-arcade_amma_actions",
]
"blob_arena-RoundResult" = [
    "blob_arena-pvp_actions",
    "arcade-arcade_actions",
    "arcade_amma-arcade_amma_actions",
]

"blob_arena-Commitment" = ["blob_arena-pvp_actions"]
"blob_arena-LastTimestamp" = ["blob_arena-pvp_actions"]
"blob_arena-PlannedAttack" = ["blob_arena-pvp_actions"]
"blob_arena-CombatEnd" = ["blob_arena-pvp_actions"]

"blob_arena-Attack" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]
"blob_arena-AttackName" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
]

"blob_arena-Tag" = [
    "blobert-blobert_actions",
    "amma_blobert-amma_blobert_actions",
    "arcade-arcade_actions",
]

"blob_arena-CollectionGroup" = [
    "blobert-blobert_actions",
    "free_blobert-free_blobert_actions",
    "amma_blobert-amma_blobert_actions",
]

"arcade-ArcadeFreeGames" = ["arcade_amma-arcade_amma_actions"]
"arcade-ArcadePaidGames" = ["arcade_amma-arcade_amma_actions"]
"arcade-ArcadeCurrentChallengeAttempt" = ["arcade_amma-arcade_amma_actions"]

"ba_permissions-Permission" = ["blob_arena-game_actions"]

"achievements-TrophyCreation" = ["blob_arena-game_actions"]
"achievements-TrophyProgression" = [
    "blob_arena-lobby_actions",
    "blob_arena-pvp_actions",
    "arcade-arcade_actions",
    "arcade_amma-arcade_amma_actions",
]

"blobert" = ["blobert-blobert_actions"]
"free_blobert" = ["free_blobert-free_blobert_actions"]
"amma_blobert" = ["amma_blobert-amma_blobert_actions"]

"arcade" = ["arcade-arcade_actions"]
"arcade_amma" = ["arcade_amma-arcade_amma_actions"]
