[account]
rpc_url = "http://localhost:5050/"
account_address = "0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

[contracts.blobert]
contract_address = "0x0"

[declare]
arena_blobert = {}
arena_blobert_minter = {}
amma_blobert = {}
attack = {}
amma_blobert_loadout = {}
arena_blobert_loadout = {}
classic_arcade = {}

[variables]
arena_contracts = []
