


[account]
rpc_url = "http://localhost:5050/"
account_address = "0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

[contracts.blobert]
contract_address = ""

[declare]
arena_blobert = {}
amma_blobert = {}
attack = {}
amma_blobert_loadout = {}
arena_blobert_loadout = {}
classic_arcade = {}

[deploy.attack] # can either be a tag of a declared contract or a 
salt = "0x0"
unique = false
calldata = ["0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"]

[deploy.amma_blobert] # can either be a tag of a declared contract or a 
salt = "0x0"
unique = false
calldata = ["0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"]

[deploy.arcade_blobert] # can either be a tag of a declared contract or a 
salt = "0x0"
unique = false
calldata = ["0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"]

[variables]
arena_contracts = []
