# The World address to index.
world_address = "0x1f4cbda175e5f687c386e096ea14afd6ef24b830578ae36b3e93a3b65e3198c"

# Default RPC URL configuration
rpc = "http://127.0.0.1:5050"

# Database configuration
# Optional: If not specified, uses in-memory database
db_dir = "torii/dev"


[sql]
historical = ["achievements-TrophyProgression"]
