tag = "blob_arena-pvp_actions"
writes = [
    "blob_arena-AvailableAttack",
    "blob_arena-CombatState",
    "blob_arena-Salts",
    "blob_arena-CombatantInfo",
    "blob_arena-CombatantState",
    "blob_arena-CombatantStats",
    "blob_arena-PlannedAttack",
    "blob_arena-Commitment",
    "blob_arena-Item",
    "blob_arena-PvPChallengeInvite",
    "blob_arena-PvPChallengeResponse",
    "blob_arena-PvPChallengeScore",
    "blob_arena-PvPCombatants",
]
