[package]
name = "ba_loadout"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
experimental-features = ["associated_item_constraints"]

[tool]
fmt.workspace = true
scarb.workspace = true

[cairo]
sierra-replace-ids = true

[dependencies]
alexandria_macros.workspace = true
starknet.workspace = true
sai_core_utils.workspace = true
sai_access.workspace = true
dojo_macros.workspace = true
dojo.workspace = true
torii_beacon.workspace = true
torii_beacon_macros.workspace = true


[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[dev-dependencies]
# dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }

[lib]
