[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/sepolia/deployment/abis/dojo-world.json"
address = "0x1eca02fecd28eef931d376376fd28fa8dc007ef7c0f101f96faf84892e34255"
transaction_hash = "0x27d0ec9252f832d38a6931632610fe19b585776f5f5a8c722ca2e70cdbc89ac"
seed = "blob-arena-0.3-alpha.5-2"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x40483d3feb95f69cc8e7f5793715bdf66b4436f22abef049422e737b8e63fdb"
class_hash = "0x3758989035782ec0d5c2aa4a54284767f53437a756a1b8a45cef6423aca76a7"
original_class_hash = "0x3758989035782ec0d5c2aa4a54284767f53437a756a1b8a45cef6423aca76a7"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-arcade_blobert_actions-64e66191.json"
reads = []
writes = [
    "ArcadeBlobert",
    "LastMint",
]
init_calldata = []
tag = "blob_arena-arcade_blobert_actions"
manifest_name = "blob_arena-arcade_blobert_actions-64e66191"

[[contracts]]
kind = "DojoContract"
address = "0x1f566a06b9b411c871fce21f02820581deb60fb023009a53cc559ecffb96eb0"
class_hash = "0x1fd3f2753e3c15f121f7ae092b4b9f16274962f6b907623a020f6afc8d33c6f"
original_class_hash = "0x1fd3f2753e3c15f121f7ae092b4b9f16274962f6b907623a020f6afc8d33c6f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-attack_actions-1aec710d.json"
reads = []
writes = ["Attack"]
init_calldata = []
tag = "blob_arena-attack_actions"
manifest_name = "blob_arena-attack_actions-1aec710d"

[[contracts]]
kind = "DojoContract"
address = "0x606c874a2b8639a99d6aae870791f459ef22ab24039a1ab33af04519963ed2"
class_hash = "0x786d687e38ba8b1c6705d4902c6c5f9879a00902aaf9518bb5c979fd7fc70dd"
original_class_hash = "0x786d687e38ba8b1c6705d4902c6c5f9879a00902aaf9518bb5c979fd7fc70dd"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-blobert_actions-6e38837a.json"
reads = []
writes = [
    "ItemMap",
    "Item",
    "Attack",
    "HasAttack",
]
init_calldata = []
tag = "blob_arena-blobert_actions"
manifest_name = "blob_arena-blobert_actions-6e38837a"

[[contracts]]
kind = "DojoContract"
address = "0x58ce145749d82d8934ac5906ca7040521bf78a1fc4f4d822b2112f05b79375d"
class_hash = "0x5099d1473224dfcd72b268708458602a152091c4f134b1657ba8d8e4ce79891"
original_class_hash = "0x5099d1473224dfcd72b268708458602a152091c4f134b1657ba8d8e4ce79891"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-item_actions-7087862a.json"
reads = []
writes = [
    "Item",
    "Attack",
    "HasAttack",
]
init_calldata = []
tag = "blob_arena-item_actions"
manifest_name = "blob_arena-item_actions-7087862a"

[[contracts]]
kind = "DojoContract"
address = "0x78e512037e5b477cc2e012a2a3b9e9bbd91e5514f23de4d62fdb09e6f9898c7"
class_hash = "0x411aa0a24e2f2a37814415d2e373b43b5f2a236f13b78a9cf91321e555b6ac4"
original_class_hash = "0x411aa0a24e2f2a37814415d2e373b43b5f2a236f13b78a9cf91321e555b6ac4"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-pvp_actions-2371c4eb.json"
reads = []
writes = [
    "AvailableAttack",
    "CombatState",
    "Salts",
    "CombatantInfo",
    "CombatantState",
    "CombatantStats",
    "PlannedAttack",
    "Commitment",
    "Item",
    "PvPChallengeInvite",
    "PvPChallengeResponse",
    "PvPChallengeScore",
    "PvPCombatants",
]
init_calldata = []
tag = "blob_arena-pvp_actions"
manifest_name = "blob_arena-pvp_actions-2371c4eb"

[[contracts]]
kind = "DojoContract"
address = "0x4cee3230c31c426a8a5b15f4567197890d3e2095f3f946f08d3d2f012d87ce5"
class_hash = "0x20e19d4c5109f543321dcae64344f671c05058c15c3c382dfce8da1da7306b7"
original_class_hash = "0x20e19d4c5109f543321dcae64344f671c05058c15c3c382dfce8da1da7306b7"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-pvp_admin_actions-2959c1bc.json"
reads = []
writes = [
    "AvailableAttack",
    "CombatState",
    "CombatantInfo",
    "CombatantState",
    "CombatantStats",
    "PvPCombatants",
]
init_calldata = []
tag = "blob_arena-pvp_admin_actions"
manifest_name = "blob_arena-pvp_admin_actions-2959c1bc"

[[models]]
kind = "DojoModel"
class_hash = "0x41940ce72738be46e8eac0d3a6cbbee6add7d4ef28a57e8101f2da906de9efd"
original_class_hash = "0x41940ce72738be46e8eac0d3a6cbbee6add7d4ef28a57e8101f2da906de9efd"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-ArcadeBlobert-773995d0.json"
tag = "blob_arena-ArcadeBlobert"
manifest_name = "blob_arena-ArcadeBlobert-773995d0"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "traits"
type = "TokenTrait"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x133004782cad0ef551aaafb0c64647e3ac8fd36661e081b15b6a96dd57e1ac3"
original_class_hash = "0x133004782cad0ef551aaafb0c64647e3ac8fd36661e081b15b6a96dd57e1ac3"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Attack-7e21e142.json"
tag = "blob_arena-Attack"
manifest_name = "blob_arena-Attack-7e21e142"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "damage"
type = "u8"
key = false

[[models.members]]
name = "speed"
type = "u8"
key = false

[[models.members]]
name = "accuracy"
type = "u8"
key = false

[[models.members]]
name = "critical"
type = "u8"
key = false

[[models.members]]
name = "stun"
type = "u8"
key = false

[[models.members]]
name = "cooldown"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x11237b6c2ba0807bc19dc2ef6613aa48e2b1bcb6e07c7953c22d8f543342dfe"
original_class_hash = "0x11237b6c2ba0807bc19dc2ef6613aa48e2b1bcb6e07c7953c22d8f543342dfe"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-AvailableAttack-32de0cec.json"
tag = "blob_arena-AvailableAttack"
manifest_name = "blob_arena-AvailableAttack-32de0cec"

[[models.members]]
name = "combatant_id"
type = "u128"
key = true

[[models.members]]
name = "attack_id"
type = "u128"
key = true

[[models.members]]
name = "available"
type = "bool"
key = false

[[models.members]]
name = "last_used"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7111b42db8a2db2c2665d8f209097484890ef92dfe4ea9f5f5c911a13b0585a"
original_class_hash = "0x7111b42db8a2db2c2665d8f209097484890ef92dfe4ea9f5f5c911a13b0585a"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatState-5fc9633c.json"
tag = "blob_arena-CombatState"
manifest_name = "blob_arena-CombatState-5fc9633c"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "round"
type = "u32"
key = false

[[models.members]]
name = "phase"
type = "Phase"
key = false

[[models.members]]
name = "block_number"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x253975837feecb6afd30571e300f170ff8fe8425617a6183863d575ac537754"
original_class_hash = "0x253975837feecb6afd30571e300f170ff8fe8425617a6183863d575ac537754"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatantInfo-5cdb2b07.json"
tag = "blob_arena-CombatantInfo"
manifest_name = "blob_arena-CombatantInfo-5cdb2b07"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "combat_id"
type = "u128"
key = false

[[models.members]]
name = "player"
type = "ContractAddress"
key = false

[[models.members]]
name = "collection_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "token_id"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x635e3c9fcf077c4aa126dd788eb686a9eb2b8fa1b297bc109ecd6514962c754"
original_class_hash = "0x635e3c9fcf077c4aa126dd788eb686a9eb2b8fa1b297bc109ecd6514962c754"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatantState-3017929c.json"
tag = "blob_arena-CombatantState"
manifest_name = "blob_arena-CombatantState-3017929c"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "stun_chance"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2feef68dea9f7e5412d1ab173d4115d5e39c8c3e1bb54b06a66b2430badfc3"
original_class_hash = "0x2feef68dea9f7e5412d1ab173d4115d5e39c8c3e1bb54b06a66b2430badfc3"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatantStats-42476be5.json"
tag = "blob_arena-CombatantStats"
manifest_name = "blob_arena-CombatantStats-42476be5"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "attack"
type = "u8"
key = false

[[models.members]]
name = "defense"
type = "u8"
key = false

[[models.members]]
name = "speed"
type = "u8"
key = false

[[models.members]]
name = "strength"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x111e01e5782262e809908bb29361195a85ec2c8e44fa84f599aed1e99d9da17"
original_class_hash = "0x111e01e5782262e809908bb29361195a85ec2c8e44fa84f599aed1e99d9da17"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Commitment-42bf7339.json"
tag = "blob_arena-Commitment"
manifest_name = "blob_arena-Commitment-42bf7339"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "commitment"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x63bdebc3c477da0bace035d17aea284161b5d08eafcf3b3b8f65d59422c62b9"
original_class_hash = "0x63bdebc3c477da0bace035d17aea284161b5d08eafcf3b3b8f65d59422c62b9"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-HasAttack-36ee741d.json"
tag = "blob_arena-HasAttack"
manifest_name = "blob_arena-HasAttack-36ee741d"

[[models.members]]
name = "item_id"
type = "u128"
key = true

[[models.members]]
name = "attack_id"
type = "u128"
key = true

[[models.members]]
name = "has"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x326ec04893f7820b22a1e393cfa0ceb972ae6dc70f99de13a852f0a037a87c9"
original_class_hash = "0x326ec04893f7820b22a1e393cfa0ceb972ae6dc70f99de13a852f0a037a87c9"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Item-44b6d01c.json"
tag = "blob_arena-Item"
manifest_name = "blob_arena-Item-44b6d01c"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "stats"
type = "Stats"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6a61e0f384bd4899fccd1e29d344a0574efc73e6fec8fe77d3f98878aa48981"
original_class_hash = "0x6a61e0f384bd4899fccd1e29d344a0574efc73e6fec8fe77d3f98878aa48981"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-ItemMap-2770c075.json"
tag = "blob_arena-ItemMap"
manifest_name = "blob_arena-ItemMap-2770c075"

[[models.members]]
name = "custom"
type = "bool"
key = true

[[models.members]]
name = "blobert_trait"
type = "BlobertTrait"
key = true

[[models.members]]
name = "blobert_trait_id"
type = "u8"
key = true

[[models.members]]
name = "item_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x504a836826a1d481870293fa67d34b2cf738e7f7986c1c172312d91e20189ec"
original_class_hash = "0x504a836826a1d481870293fa67d34b2cf738e7f7986c1c172312d91e20189ec"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-LastMint-237efc09.json"
tag = "blob_arena-LastMint"
manifest_name = "blob_arena-LastMint-237efc09"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x359085612d3762cefb03aec1d7765f126b24adc9fd36f9b002ab16a4a532ae9"
original_class_hash = "0x359085612d3762cefb03aec1d7765f126b24adc9fd36f9b002ab16a4a532ae9"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PlannedAttack-76d19ab4.json"
tag = "blob_arena-PlannedAttack"
manifest_name = "blob_arena-PlannedAttack-76d19ab4"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "attack"
type = "u128"
key = false

[[models.members]]
name = "target"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2cb397b411cb69db12a581dcc615a731468aa11232ddcaf46340de541b2e300"
original_class_hash = "0x2cb397b411cb69db12a581dcc615a731468aa11232ddcaf46340de541b2e300"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPChallengeInvite-61052667.json"
tag = "blob_arena-PvPChallengeInvite"
manifest_name = "blob_arena-PvPChallengeInvite-61052667"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "sender"
type = "ContractAddress"
key = false

[[models.members]]
name = "receiver"
type = "ContractAddress"
key = false

[[models.members]]
name = "collection_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "combatant"
type = "u128"
key = false

[[models.members]]
name = "phase_time"
type = "u64"
key = false

[[models.members]]
name = "open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5ebf2d5d92c53e341ca93fee0eff719447aa21e85bd6a4cd1ddca46456e7604"
original_class_hash = "0x5ebf2d5d92c53e341ca93fee0eff719447aa21e85bd6a4cd1ddca46456e7604"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPChallengeResponse-1cf0daf6.json"
tag = "blob_arena-PvPChallengeResponse"
manifest_name = "blob_arena-PvPChallengeResponse-1cf0daf6"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "combatant"
type = "u128"
key = false

[[models.members]]
name = "open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57471ad6b0be8c146a795b8188738d7640b974205a7290a4d470286c02928d4"
original_class_hash = "0x57471ad6b0be8c146a795b8188738d7640b974205a7290a4d470286c02928d4"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPChallengeScore-17ec3a4a.json"
tag = "blob_arena-PvPChallengeScore"
manifest_name = "blob_arena-PvPChallengeScore-17ec3a4a"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "collection_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_high"
type = "u128"
key = true

[[models.members]]
name = "token_low"
type = "u128"
key = true

[[models.members]]
name = "wins"
type = "u64"
key = false

[[models.members]]
name = "losses"
type = "u64"
key = false

[[models.members]]
name = "max_consecutive_wins"
type = "u64"
key = false

[[models.members]]
name = "current_consecutive_wins"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x528ca49397db809f3c265259670e9e9e5bdbc864364f107853c0ae80e3c9e0c"
original_class_hash = "0x528ca49397db809f3c265259670e9e9e5bdbc864364f107853c0ae80e3c9e0c"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPCombatants-1b472645.json"
tag = "blob_arena-PvPCombatants"
manifest_name = "blob_arena-PvPCombatants-1b472645"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "combatants"
type = "(u128, u128)"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57389fae080bc06729acb394683c00a4667821b33669da2aaea7a1ed52b4f8f"
original_class_hash = "0x57389fae080bc06729acb394683c00a4667821b33669da2aaea7a1ed52b4f8f"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-RandomSeed-586ad963.json"
tag = "blob_arena-RandomSeed"
manifest_name = "blob_arena-RandomSeed-586ad963"

[[models.members]]
name = "key"
type = "bool"
key = true

[[models.members]]
name = "value"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x46b6b5cffc45b50cbb94ba47367380349a47a995d9c52fdf304e394868caa4a"
original_class_hash = "0x46b6b5cffc45b50cbb94ba47367380349a47a995d9c52fdf304e394868caa4a"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Salts-10b0ca3a.json"
tag = "blob_arena-Salts"
manifest_name = "blob_arena-Salts-10b0ca3a"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "salts"
type = "Array<felt252>"
key = false
