[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/sepolia/deployment/abis/dojo-world.json"
address = "0x5f9867afd8f1fd4bed55c551ce07b09cd7d33f81e3eea68fb9f9e10378a7e20"
transaction_hash = "0x7bd89860e7ad77f23272c87f6da263921acab9e101e037eb1fd500b6b3bbdcd"
block_number = 189551
seed = "blob-arena-0.4-alpha.5-12"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x69f1bc4ee2aa9e2e18ed2503247050b9aa42df60dd1ecf8ed1102b8f5b012da"
class_hash = "0x62a7b8923e67b96b9470d91e7aa104de3cd4083443431c4b31f5efcf04db147"
original_class_hash = "0x62a7b8923e67b96b9470d91e7aa104de3cd4083443431c4b31f5efcf04db147"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-arcade_blobert_actions-64e66191.json"
reads = []
writes = [
    "ArcadeBlobert",
    "LastMint",
    "AMMABlobert",
]
init_calldata = []
tag = "blob_arena-arcade_blobert_actions"
manifest_name = "blob_arena-arcade_blobert_actions-64e66191"

[[contracts]]
kind = "DojoContract"
address = "0x95b9dd84bd724216f50d0f24ef2b6956d2a2ff9d8c4a4a98f1e9339db32ee"
class_hash = "0x1fd3f2753e3c15f121f7ae092b4b9f16274962f6b907623a020f6afc8d33c6f"
original_class_hash = "0x1fd3f2753e3c15f121f7ae092b4b9f16274962f6b907623a020f6afc8d33c6f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-attack_actions-1aec710d.json"
reads = []
writes = ["Attack"]
init_calldata = []
tag = "blob_arena-attack_actions"
manifest_name = "blob_arena-attack_actions-1aec710d"

[[contracts]]
kind = "DojoContract"
address = "0xbdb3704292c8f077e48c6a6493e5016a7a91e68c4d46913b9861d84787dac9"
class_hash = "0x2c8cb7652be80b6b7b8bd0c8b87c8ab1d2a625999e68c23d3b1d06b6641aae9"
original_class_hash = "0x2c8cb7652be80b6b7b8bd0c8b87c8ab1d2a625999e68c23d3b1d06b6641aae9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-blobert_actions-6e38837a.json"
reads = []
writes = [
    "ItemMap",
    "Item",
    "Attack",
    "HasAttack",
]
init_calldata = []
tag = "blob_arena-blobert_actions"
manifest_name = "blob_arena-blobert_actions-6e38837a"

[[contracts]]
kind = "DojoContract"
address = "0x48304ba4cf26a35ef51b16b3f1b1e87c1d885888a4dc3934a3900062063e615"
class_hash = "0x5099d1473224dfcd72b268708458602a152091c4f134b1657ba8d8e4ce79891"
original_class_hash = "0x5099d1473224dfcd72b268708458602a152091c4f134b1657ba8d8e4ce79891"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-item_actions-7087862a.json"
reads = []
writes = [
    "Item",
    "Attack",
    "HasAttack",
]
init_calldata = []
tag = "blob_arena-item_actions"
manifest_name = "blob_arena-item_actions-7087862a"

[[contracts]]
kind = "DojoContract"
address = "0x6d61217ac6f0c8dc2cc91dfc57512ac4dac8914e12c58cd22f092e05380a23a"
class_hash = "0x48bcc86e4cf2d1215b4dc5818014f502db06decf0d90d02b88118e888eebf3a"
original_class_hash = "0x48bcc86e4cf2d1215b4dc5818014f502db06decf0d90d02b88118e888eebf3a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-pvp_actions-2371c4eb.json"
reads = []
writes = [
    "AvailableAttack",
    "CombatState",
    "Salts",
    "CombatantInfo",
    "CombatantState",
    "CombatantStats",
    "PlannedAttack",
    "Commitment",
    "Item",
    "PvPChallengeInvite",
    "PvPChallengeResponse",
    "PvPChallengeScore",
    "PvPCombatants",
    "AttackResult",
]
init_calldata = []
tag = "blob_arena-pvp_actions"
manifest_name = "blob_arena-pvp_actions-2371c4eb"

[[contracts]]
kind = "DojoContract"
address = "0x79c389702f3abe9d9e3f37d43223cfabb12610ee7ba70ab3329bc17e8116bad"
class_hash = "0x20e19d4c5109f543321dcae64344f671c05058c15c3c382dfce8da1da7306b7"
original_class_hash = "0x20e19d4c5109f543321dcae64344f671c05058c15c3c382dfce8da1da7306b7"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/blob_arena-pvp_admin_actions-2959c1bc.json"
reads = []
writes = [
    "AvailableAttack",
    "CombatState",
    "CombatantInfo",
    "CombatantState",
    "CombatantStats",
    "PvPCombatants",
]
init_calldata = []
tag = "blob_arena-pvp_admin_actions"
manifest_name = "blob_arena-pvp_admin_actions-2959c1bc"

[[models]]
kind = "DojoModel"
class_hash = "0x38b0368ce6d3fb45c50c7d63e69320e1e9b400a145d4bdfc5187bf25bb03ab"
original_class_hash = "0x38b0368ce6d3fb45c50c7d63e69320e1e9b400a145d4bdfc5187bf25bb03ab"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-AMMABlobert-602af421.json"
tag = "blob_arena-AMMABlobert"
manifest_name = "blob_arena-AMMABlobert-602af421"

[[models.members]]
name = "fighter_id"
type = "u8"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "custom_id"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x41940ce72738be46e8eac0d3a6cbbee6add7d4ef28a57e8101f2da906de9efd"
original_class_hash = "0x41940ce72738be46e8eac0d3a6cbbee6add7d4ef28a57e8101f2da906de9efd"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-ArcadeBlobert-773995d0.json"
tag = "blob_arena-ArcadeBlobert"
manifest_name = "blob_arena-ArcadeBlobert-773995d0"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "traits"
type = "TokenTrait"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x133004782cad0ef551aaafb0c64647e3ac8fd36661e081b15b6a96dd57e1ac3"
original_class_hash = "0x133004782cad0ef551aaafb0c64647e3ac8fd36661e081b15b6a96dd57e1ac3"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Attack-7e21e142.json"
tag = "blob_arena-Attack"
manifest_name = "blob_arena-Attack-7e21e142"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "damage"
type = "u8"
key = false

[[models.members]]
name = "speed"
type = "u8"
key = false

[[models.members]]
name = "accuracy"
type = "u8"
key = false

[[models.members]]
name = "critical"
type = "u8"
key = false

[[models.members]]
name = "stun"
type = "u8"
key = false

[[models.members]]
name = "cooldown"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5372afdc2683e01439cd954c22e00c68a15ecfa09de261d0807dc01fe4e36c0"
original_class_hash = "0x5372afdc2683e01439cd954c22e00c68a15ecfa09de261d0807dc01fe4e36c0"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-AttackResult-13e6ce9d.json"
tag = "blob_arena-AttackResult"
manifest_name = "blob_arena-AttackResult-13e6ce9d"

[[models.members]]
name = "combatant_id"
type = "u128"
key = true

[[models.members]]
name = "round"
type = "u32"
key = true

[[models.members]]
name = "attack_id"
type = "u128"
key = false

[[models.members]]
name = "target"
type = "u128"
key = false

[[models.members]]
name = "effect"
type = "u8"
key = false

[[models.members]]
name = "damage"
type = "u8"
key = false

[[models.members]]
name = "stun"
type = "u8"
key = false

[[models.members]]
name = "critical"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x11237b6c2ba0807bc19dc2ef6613aa48e2b1bcb6e07c7953c22d8f543342dfe"
original_class_hash = "0x11237b6c2ba0807bc19dc2ef6613aa48e2b1bcb6e07c7953c22d8f543342dfe"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-AvailableAttack-32de0cec.json"
tag = "blob_arena-AvailableAttack"
manifest_name = "blob_arena-AvailableAttack-32de0cec"

[[models.members]]
name = "combatant_id"
type = "u128"
key = true

[[models.members]]
name = "attack_id"
type = "u128"
key = true

[[models.members]]
name = "available"
type = "bool"
key = false

[[models.members]]
name = "last_used"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7111b42db8a2db2c2665d8f209097484890ef92dfe4ea9f5f5c911a13b0585a"
original_class_hash = "0x7111b42db8a2db2c2665d8f209097484890ef92dfe4ea9f5f5c911a13b0585a"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatState-5fc9633c.json"
tag = "blob_arena-CombatState"
manifest_name = "blob_arena-CombatState-5fc9633c"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "round"
type = "u32"
key = false

[[models.members]]
name = "phase"
type = "Phase"
key = false

[[models.members]]
name = "block_number"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x253975837feecb6afd30571e300f170ff8fe8425617a6183863d575ac537754"
original_class_hash = "0x253975837feecb6afd30571e300f170ff8fe8425617a6183863d575ac537754"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatantInfo-5cdb2b07.json"
tag = "blob_arena-CombatantInfo"
manifest_name = "blob_arena-CombatantInfo-5cdb2b07"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "combat_id"
type = "u128"
key = false

[[models.members]]
name = "player"
type = "ContractAddress"
key = false

[[models.members]]
name = "collection_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "token_id"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x635e3c9fcf077c4aa126dd788eb686a9eb2b8fa1b297bc109ecd6514962c754"
original_class_hash = "0x635e3c9fcf077c4aa126dd788eb686a9eb2b8fa1b297bc109ecd6514962c754"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatantState-3017929c.json"
tag = "blob_arena-CombatantState"
manifest_name = "blob_arena-CombatantState-3017929c"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "stun_chance"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2feef68dea9f7e5412d1ab173d4115d5e39c8c3e1bb54b06a66b2430badfc3"
original_class_hash = "0x2feef68dea9f7e5412d1ab173d4115d5e39c8c3e1bb54b06a66b2430badfc3"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-CombatantStats-42476be5.json"
tag = "blob_arena-CombatantStats"
manifest_name = "blob_arena-CombatantStats-42476be5"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "attack"
type = "u8"
key = false

[[models.members]]
name = "defense"
type = "u8"
key = false

[[models.members]]
name = "speed"
type = "u8"
key = false

[[models.members]]
name = "strength"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x111e01e5782262e809908bb29361195a85ec2c8e44fa84f599aed1e99d9da17"
original_class_hash = "0x111e01e5782262e809908bb29361195a85ec2c8e44fa84f599aed1e99d9da17"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Commitment-42bf7339.json"
tag = "blob_arena-Commitment"
manifest_name = "blob_arena-Commitment-42bf7339"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "commitment"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x63bdebc3c477da0bace035d17aea284161b5d08eafcf3b3b8f65d59422c62b9"
original_class_hash = "0x63bdebc3c477da0bace035d17aea284161b5d08eafcf3b3b8f65d59422c62b9"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-HasAttack-36ee741d.json"
tag = "blob_arena-HasAttack"
manifest_name = "blob_arena-HasAttack-36ee741d"

[[models.members]]
name = "item_id"
type = "u128"
key = true

[[models.members]]
name = "attack_id"
type = "u128"
key = true

[[models.members]]
name = "has"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x326ec04893f7820b22a1e393cfa0ceb972ae6dc70f99de13a852f0a037a87c9"
original_class_hash = "0x326ec04893f7820b22a1e393cfa0ceb972ae6dc70f99de13a852f0a037a87c9"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Item-44b6d01c.json"
tag = "blob_arena-Item"
manifest_name = "blob_arena-Item-44b6d01c"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "stats"
type = "Stats"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1c6d7140192b776d5fd3b5041437760f025ba12d02bb535d4999f6e61f734b4"
original_class_hash = "0x1c6d7140192b776d5fd3b5041437760f025ba12d02bb535d4999f6e61f734b4"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-ItemMap-2770c075.json"
tag = "blob_arena-ItemMap"
manifest_name = "blob_arena-ItemMap-2770c075"

[[models.members]]
name = "trait_type"
type = "felt252"
key = true

[[models.members]]
name = "blobert_trait"
type = "BlobertTrait"
key = true

[[models.members]]
name = "blobert_trait_id"
type = "u8"
key = true

[[models.members]]
name = "item_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x504a836826a1d481870293fa67d34b2cf738e7f7986c1c172312d91e20189ec"
original_class_hash = "0x504a836826a1d481870293fa67d34b2cf738e7f7986c1c172312d91e20189ec"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-LastMint-237efc09.json"
tag = "blob_arena-LastMint"
manifest_name = "blob_arena-LastMint-237efc09"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x359085612d3762cefb03aec1d7765f126b24adc9fd36f9b002ab16a4a532ae9"
original_class_hash = "0x359085612d3762cefb03aec1d7765f126b24adc9fd36f9b002ab16a4a532ae9"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PlannedAttack-76d19ab4.json"
tag = "blob_arena-PlannedAttack"
manifest_name = "blob_arena-PlannedAttack-76d19ab4"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "attack"
type = "u128"
key = false

[[models.members]]
name = "target"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2cb397b411cb69db12a581dcc615a731468aa11232ddcaf46340de541b2e300"
original_class_hash = "0x2cb397b411cb69db12a581dcc615a731468aa11232ddcaf46340de541b2e300"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPChallengeInvite-61052667.json"
tag = "blob_arena-PvPChallengeInvite"
manifest_name = "blob_arena-PvPChallengeInvite-61052667"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "sender"
type = "ContractAddress"
key = false

[[models.members]]
name = "receiver"
type = "ContractAddress"
key = false

[[models.members]]
name = "collection_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "combatant"
type = "u128"
key = false

[[models.members]]
name = "phase_time"
type = "u64"
key = false

[[models.members]]
name = "open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5ebf2d5d92c53e341ca93fee0eff719447aa21e85bd6a4cd1ddca46456e7604"
original_class_hash = "0x5ebf2d5d92c53e341ca93fee0eff719447aa21e85bd6a4cd1ddca46456e7604"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPChallengeResponse-1cf0daf6.json"
tag = "blob_arena-PvPChallengeResponse"
manifest_name = "blob_arena-PvPChallengeResponse-1cf0daf6"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "combatant"
type = "u128"
key = false

[[models.members]]
name = "open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57471ad6b0be8c146a795b8188738d7640b974205a7290a4d470286c02928d4"
original_class_hash = "0x57471ad6b0be8c146a795b8188738d7640b974205a7290a4d470286c02928d4"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPChallengeScore-17ec3a4a.json"
tag = "blob_arena-PvPChallengeScore"
manifest_name = "blob_arena-PvPChallengeScore-17ec3a4a"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "collection_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_high"
type = "u128"
key = true

[[models.members]]
name = "token_low"
type = "u128"
key = true

[[models.members]]
name = "wins"
type = "u64"
key = false

[[models.members]]
name = "losses"
type = "u64"
key = false

[[models.members]]
name = "max_consecutive_wins"
type = "u64"
key = false

[[models.members]]
name = "current_consecutive_wins"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x528ca49397db809f3c265259670e9e9e5bdbc864364f107853c0ae80e3c9e0c"
original_class_hash = "0x528ca49397db809f3c265259670e9e9e5bdbc864364f107853c0ae80e3c9e0c"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-PvPCombatants-1b472645.json"
tag = "blob_arena-PvPCombatants"
manifest_name = "blob_arena-PvPCombatants-1b472645"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "combatants"
type = "(u128, u128)"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x57389fae080bc06729acb394683c00a4667821b33669da2aaea7a1ed52b4f8f"
original_class_hash = "0x57389fae080bc06729acb394683c00a4667821b33669da2aaea7a1ed52b4f8f"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-RandomSeed-586ad963.json"
tag = "blob_arena-RandomSeed"
manifest_name = "blob_arena-RandomSeed-586ad963"

[[models.members]]
name = "key"
type = "bool"
key = true

[[models.members]]
name = "value"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x266ffa44316fe2fddf38b773d329507b41a413efee956e305c73c32ffefe4af"
original_class_hash = "0x266ffa44316fe2fddf38b773d329507b41a413efee956e305c73c32ffefe4af"
abi = "manifests/sepolia/deployment/abis/models/blob_arena-Salts-10b0ca3a.json"
tag = "blob_arena-Salts"
manifest_name = "blob_arena-Salts-10b0ca3a"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "salts"
type = "Option<Array<felt252>>"
key = false
