kind = "DojoModel"
class_hash = "0x33f9dd9f192f3e4db9970a173a13bdd8ef165979d0c64023ef37a8e47e51a37"
original_class_hash = "0x33f9dd9f192f3e4db9970a173a13bdd8ef165979d0c64023ef37a8e47e51a37"
abi = "manifests/dev/abis/base/models/blob_arena_models_pvp_pv_p_combatants.json"
name = "blob_arena::models::pvp::pv_p_combatants"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "combatants"
type = "(u128, u128)"
key = false
