kind = "DojoModel"
class_hash = "0x4cde3af16e5c0a3807e6027e8d7422958bc1634b5a95b063b96f3c3d5dc5317"
original_class_hash = "0x4cde3af16e5c0a3807e6027e8d7422958bc1634b5a95b063b96f3c3d5dc5317"
abi = "manifests/dev/abis/base/models/blob_arena_models_item_has_attack.json"
name = "blob_arena::models::item::has_attack"

[[members]]
name = "item_id"
type = "u128"
key = true

[[members]]
name = "attack_id"
type = "u128"
key = true

[[members]]
name = "has"
type = "bool"
key = false
