kind = "DojoModel"
class_hash = "0x6d14b06adadef31e64972ad44b71c970aabb116dbbb98e7eb740b83bd0943e9"
original_class_hash = "0x6d14b06adadef31e64972ad44b71c970aabb116dbbb98e7eb740b83bd0943e9"
abi = "manifests/dev/abis/base/models/blob_arena_models_pvp_pv_p_challenge_invite.json"
name = "blob_arena::models::pvp::pv_p_challenge_invite"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "sender"
type = "ContractAddress"
key = false

[[members]]
name = "receiver"
type = "ContractAddress"
key = false

[[members]]
name = "collection_address"
type = "ContractAddress"
key = false

[[members]]
name = "combatant"
type = "u128"
key = false

[[members]]
name = "phase_time"
type = "u64"
key = false

[[members]]
name = "open"
type = "bool"
key = false
