kind = "DojoModel"
class_hash = "0x4892ad7fae019672656f8a94f0a6659ce1a0fb1a9be4202582832f62e11d6ee"
original_class_hash = "0x4892ad7fae019672656f8a94f0a6659ce1a0fb1a9be4202582832f62e11d6ee"
abi = "manifests/dev/abis/base/models/blob_arena_models_pvp_pv_p_challenge_response.json"
name = "blob_arena::models::pvp::pv_p_challenge_response"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "combatant"
type = "u128"
key = false

[[members]]
name = "open"
type = "bool"
key = false
