kind = "DojoModel"
class_hash = "0x52db709a76c5b369c4b2747bb436f331a03b7269445d0aadb355e0c88fa804a"
original_class_hash = "0x52db709a76c5b369c4b2747bb436f331a03b7269445d0aadb355e0c88fa804a"
abi = "manifests/dev/abis/base/models/blob_arena_models_combatant_combatant_stats.json"
name = "blob_arena::models::combatant::combatant_stats"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "attack"
type = "u8"
key = false

[[members]]
name = "defense"
type = "u8"
key = false

[[members]]
name = "speed"
type = "u8"
key = false

[[members]]
name = "strength"
type = "u8"
key = false
