kind = "DojoModel"
class_hash = "0x69304c0476bdb2dec54afa6983183bba425b05948b91bfd27fddd1fb420139"
original_class_hash = "0x69304c0476bdb2dec54afa6983183bba425b05948b91bfd27fddd1fb420139"
abi = "manifests/dev/abis/base/models/blob_arena_models_attack_attack.json"
name = "blob_arena::models::attack::attack"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "damage"
type = "u8"
key = false

[[members]]
name = "speed"
type = "u8"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "critical"
type = "u8"
key = false

[[members]]
name = "stun"
type = "u8"
key = false

[[members]]
name = "cooldown"
type = "u8"
key = false
