kind = "DojoModel"
class_hash = "0x243e065a87c88a5281ab34e355e0b360d4100867c2adb977790c360a79949d9"
original_class_hash = "0x243e065a87c88a5281ab34e355e0b360d4100867c2adb977790c360a79949d9"
abi = "manifests/dev/abis/base/models/blob_arena_models_combat_salts.json"
name = "blob_arena::models::combat::salts"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "salts"
type = "Array<felt252>"
key = false
