kind = "DojoModel"
class_hash = "0x2414ca790739f7b77342ddb3c904d7ba2141df23d0e413d0c6a2ad945f3969c"
original_class_hash = "0x2414ca790739f7b77342ddb3c904d7ba2141df23d0e413d0c6a2ad945f3969c"
abi = "manifests/dev/abis/base/models/blob_arena_models_pvp_pv_p_challenge_score.json"
name = "blob_arena::models::pvp::pv_p_challenge_score"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "collection_address"
type = "ContractAddress"
key = true

[[members]]
name = "token_high"
type = "u128"
key = true

[[members]]
name = "token_low"
type = "u128"
key = true

[[members]]
name = "wins"
type = "u64"
key = false

[[members]]
name = "losses"
type = "u64"
key = false

[[members]]
name = "max_consecutive_wins"
type = "u64"
key = false

[[members]]
name = "current_consecutive_wins"
type = "u64"
key = false
