kind = "DojoModel"
class_hash = "0x2c2f21a9f623112c4026201803e62674f3f5d3a7cc94da5b544622bb232023b"
original_class_hash = "0x2c2f21a9f623112c4026201803e62674f3f5d3a7cc94da5b544622bb232023b"
abi = "manifests/dev/abis/base/models/blob_arena_models_combat_combat_state.json"
name = "blob_arena::models::combat::combat_state"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "round"
type = "u32"
key = false

[[members]]
name = "phase"
type = "Phase"
key = false

[[members]]
name = "block_number"
type = "u64"
key = false
