kind = "DojoModel"
class_hash = "0x406a86342e9ae38b2515e8d78e65b6ac19c46de9e834a7e771da3b3f2820248"
original_class_hash = "0x406a86342e9ae38b2515e8d78e65b6ac19c46de9e834a7e771da3b3f2820248"
abi = "manifests/dev/abis/base/models/blob_arena_models_combatant_combatant_info.json"
name = "blob_arena::models::combatant::combatant_info"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "combat_id"
type = "u128"
key = false

[[members]]
name = "player"
type = "ContractAddress"
key = false

[[members]]
name = "collection_address"
type = "ContractAddress"
key = false

[[members]]
name = "token_id"
type = "u256"
key = false
