kind = "DojoModel"
class_hash = "0xb7d20a0d4322c37b7ce38069e509c3e588e38bea4e6c544483c441f03999d9"
original_class_hash = "0xb7d20a0d4322c37b7ce38069e509c3e588e38bea4e6c544483c441f03999d9"
abi = "manifests/dev/abis/base/models/blob_arena_models_combatant_planned_attack.json"
name = "blob_arena::models::combatant::planned_attack"

[[members]]
name = "id"
type = "u128"
key = true

[[members]]
name = "attack"
type = "u128"
key = false

[[members]]
name = "target"
type = "u128"
key = false
