// Generated by dojo-bindgen on Mon, 1 Jul 2024 11:14:10 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `blob_arena::collections::blobert::external::Seed` struct
[Serializable]
public struct Seed {
    public byte background;
    public byte armour;
    public byte jewelry;
    public byte mask;
    public byte weapon;
}

// Type definition for `blob_arena::collections::blobert::external::TokenTrait` enum
public abstract record TokenTrait() : Enum {
    public record Regular(Seed value) : TokenTrait;
    public record Custom(byte value) : TokenTrait;
}


// Model definition for `blob_arena::collections::arcade_blobert::blobert::ArcadeBlobert` model
public class ArcadeBlobert : ModelInstance {
    [ModelField("token_id")]
    public BigInteger token_id;

    [ModelField("owner")]
    public FieldElement owner;

    [ModelField("traits")]
    public TokenTrait traits;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        