// Generated by dojo-bindgen on Mon, 1 Jul 2024 21:02:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::models::attack::Attack` model
public class Attack : ModelInstance {
    [ModelField("id")]
    public BigInteger id;

    [ModelField("name")]
    public string name;

    [ModelField("damage")]
    public byte damage;

    [ModelField("speed")]
    public byte speed;

    [ModelField("accuracy")]
    public byte accuracy;

    [ModelField("critical")]
    public byte critical;

    [ModelField("stun")]
    public byte stun;

    [ModelField("cooldown")]
    public byte cooldown;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        