// Generated by dojo-bindgen on Fri, 28 Jun 2024 10:26:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::models::attack::AvailableAttack` model
public class AvailableAttack : ModelInstance {
    [ModelField("combatant_id")]
    public BigInteger combatant_id;

    [ModelField("attack_id")]
    public BigInteger attack_id;

    [ModelField("available")]
    public bool available;

    [ModelField("last_used")]
    public uint last_used;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        