// Generated by dojo-bindgen on Wed, 3 Jul 2024 22:32:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::models::combatant::CombatantStats` model
public class CombatantStats : ModelInstance {
    [ModelField("id")]
    public BigInteger id;

    [ModelField("attack")]
    public byte attack;

    [ModelField("defense")]
    public byte defense;

    [ModelField("speed")]
    public byte speed;

    [ModelField("strength")]
    public byte strength;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        