// Generated by dojo-bindgen on Mon, 1 Jul 2024 21:02:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `blob_arena::models::combat::Phase` enum
public abstract record Phase() : Enum {
    public record Setup() : Phase;
    public record Commit() : Phase;
    public record Reveal() : Phase;
    public record Ended(BigInteger value) : Phase;
}


// Model definition for `blob_arena::models::combat::CombatState` model
public class CombatState : ModelInstance {
    [ModelField("id")]
    public BigInteger id;

    [ModelField("round")]
    public uint round;

    [ModelField("phase")]
    public Phase phase;

    [ModelField("block_number")]
    public ulong block_number;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        