// Generated by dojo-bindgen on Fri, 28 Jun 2024 10:26:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `blob_arena::components::stats::Stats` struct
[Serializable]
public struct Stats {
    public byte attack;
    public byte defense;
    public byte speed;
    public byte strength;
}


// Model definition for `blob_arena::models::item::Item` model
public class Item : ModelInstance {
    [ModelField("id")]
    public BigInteger id;

    [ModelField("name")]
    public string name;

    [ModelField("stats")]
    public Stats stats;

    [ModelField("attacks")]
    public BigInteger[] attacks;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        