// Generated by dojo-bindgen on Fri, 28 Jun 2024 10:26:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::collections::blobert::items::ItemMap` model
public class ItemMap : ModelInstance {
    [ModelField("blobert_trait_id")]
    public BigInteger blobert_trait_id;

    [ModelField("item_id")]
    public BigInteger item_id;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        