// Generated by dojo-bindgen on Wed, 3 Jul 2024 22:32:26 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::collections::arcade_blobert::mint::LastMint` model
public class LastMint : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("timestamp")]
    public ulong timestamp;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        