// Generated by dojo-bindgen on Mon, 1 Jul 2024 21:02:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::models::pvp::PvPChallengeResponse` model
public class PvPChallengeResponse : ModelInstance {
    [ModelField("id")]
    public BigInteger id;

    [ModelField("combatant")]
    public BigInteger combatant;

    [ModelField("open")]
    public bool open;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        