// Generated by dojo-bindgen on Wed, 26 Jun 2024 09:53:14 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `blob_arena::models::warrior::WarriorItems` model
public class WarriorItems : ModelInstance {
    [ModelField("id")]
    public BigInteger id;

    [ModelField("items")]
    public BigInteger[] items;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        