[package]
name = "ba_utils"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
experimental-features = [
    "coupons",
    "negative_impls",
    "associated_item_constraints",
]

[tool]
fmt.workspace = true
scarb.workspace = true

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
sai_core_utils.workspace = true
sai_packing.workspace = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[dev-dependencies]
# dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.2" }

[lib]
